# nginx for swoole/php-fpm
FROM nginx:1.13.6-alpine

ARG TIMEZONE
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache tzdata  && \ 
    echo "${TIMEZONE}" > /etc/timezone && \    
    ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime

COPY image-files/ /

ADD docker-nginx-entrypoint /docker-nginx-entrypoint

CMD sh docker-nginx-entrypoint